server:
  port: 9200

spring:
  application:
    name: product-service
  boot:
    admin:
      client:
        url: http://localhost:8769
  zipkin:
    base-url: http://127.0.0.1:9411/

  sleuth:
    sampler:
      percentage: 1.0


eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.52:8762/eureka/
